version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Build and run custom Dockerfile
  splitnn_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splitnn_server
    volumes:
      - /var/splitnn:/var/splitnn
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres

volumes:
  postgres_data: