# Generated by Django 5.1.3 on 2024-11-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data_transfer_len", models.IntegerField()),
                (
                    "target_source_client",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("direction_to_server", models.BooleanField(default=False)),
                (
                    "source_method",
                    models.CharField(default=None, max_length=255, null=True),
                ),
            ],
        ),
    ]
