# Generated by Django 5.1.3 on 2024-12-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_logger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("training", "training"),
                            ("reset", "reset"),
                            ("validation", "validation"),
                            ("error", "error"),
                        ],
                        default="training",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("loss", models.FloatField(default=0)),
                ("epoch", models.IntegerField(default=0)),
                ("server_epoch", models.IntegerField(default=0)),
            ],
        ),
    ]
