# Generated by Django 5.1.3 on 2024-12-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_logger", "0002_traininglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="last_communication_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="traininglog",
            name="last_whole_training_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="traininglog",
            name="training_time",
            field=models.FloatField(default=0),
        ),
    ]
